source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "occivink/kakoune-sudo-write" %{ alias global sw sudo-write }
plug "base16-project/base16-kakoune" theme config %{
	colorscheme base16-heetch
}
plug "alexherbo2/surround.kak" %{
	# restore original functionality by pressing m twice
	map global surround m m
	map global normal m ":enter-user-mode surround<ret>"
}
plug "alexherbo2/auto-pairs.kak" %{ enable-auto-pairs }
plug "andreyorst/smarttab.kak" %{
	hook global BufCreate .* %{
		smarttab
		editorconfig-load
		set buffer aligntab false
		autoconfigtab
	}
}
plug "leperdu/kakboard" %{ hook global WinCreate .* %{ kakboard-enable } }
plug "kak-lsp/kak-lsp" do %{ cargo install --locked --force --path . } config %{
	hook global WinSetOption filetype=(clojure|c|cpp|python|go) %{
		lsp-enable-window
		lsp-auto-hover-enable
	}
	map global normal <c-l> ":enter-user-mode lsp<ret>"
}
plug "alexherbo2/alacritty.kak"
plug "occivink/kakoune-snippets"
plug "JJK96/kakoune-emmet" config %{
	hook global WinSetOption filetype=html %{
		emmet-enable-autocomplete
	}
}

# initialize kampliment, for remote control
evaluate-commands %sh{ kamp init -a }
map global user g ":connect terminal-popup kamp-grep<ret>" -docstring "grep files…"
map global user f ":connect terminal-popup kamp-files<ret>" -docstring "find files…"
map global user b ":connect terminal-popup kamp-buffers<ret>" -docstring "search buffer…"

# sorry clippy
set global ui_options terminal_assistant=none
set global tabstop 2

# auto format files
hook global WinSetOption filetype=(c|cpp) %{ set window formatcmd clang-format }
hook global WinSetOption filetype=python %{ set window formatcmd yapf }
hook global WinSetOption filetype=go %{ set window formatcmd gofmt }
hook global BufWritePre .*\.(c|cpp|py|go)$ %{ format }

# auto format packages.x86_64 in demolinux source
hook global WinCreate .*packages\.x86_64 %{ set window formatcmd sort }
hook global BufWritePre .*packages\.x86_64 %{ format }

# YOU WILL NOT FUCK MY EYES
face global MenuBackground Default
face global MenuInfo Default
face global Information Default

# use tab and shift-tab to navigate the completion menu
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }
