source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "occivink/kakoune-sudo-write" %{ alias global sw sudo-write }
plug "base16-project/base16-kakoune" theme config %{
	colorscheme base16-heetch
}
plug "alexherbo2/surround.kak" %{
	map global normal <c-]> ":enter-user-mode surround<ret>"
}
plug "alexherbo2/auto-pairs.kak" %{ enable-auto-pairs }
plug "andreyorst/smarttab.kak" %{
	hook global BufCreate .* %{
		smarttab
		editorconfig-load
		set buffer aligntab false
		autoconfigtab
	}
}
plug "leperdu/kakboard" %{ hook global WinCreate .* %{ kakboard-enable } }
plug "kak-lsp/kak-lsp" do %{ cargo install --locked --force --path . } config %{
	set buffer lsp_config %{
		[language.clojure]
		filetypes = ["clojure"]
		roots = ["project.clj", "deps.edn", ".git/"]
		command = "clojure-lsp"

		[language.c_cpp]
		filetypes = ["c", "cpp"]
		roots = ["compile_commands.json", ".git/"]
		command = "clangd"
	}
	hook global WinSetOption filetype=(clojure) %{
		lsp-enable-window
	}
}
plug "gustavo-hms/luar" %{
	plug "gustavo-hms/peneira" %{
		require-module peneira

		define-command peneira-grep %{
			prompt "find: " %{
				peneira "line: " "rg -n %val{text}" %{
				  lua %arg{1} %{
			  		local file, line = arg[1]:match("([^:]+):(%d+):")
						kak.edit(file, line)
				  }
				}
			}
		}

		declare-user-mode pick
		map global normal <a-g> ":enter-user-mode pick<ret>"
		map global pick f ":peneira-files<ret>" -docstring "find file…"
		map global pick g ":peneira-grep<ret>" -docstring "find in file…"
		map global pick t ":kaktree-toggle<ret>" -docstring "tree…"
	}
}
plug "andreyorst/kaktree" config %{
	hook global WinSetOption filetype=kaktree %{
		set window modelinefmt ''
	}
	kaktree-enable
	set global kaktree_show_help false
	hook global -once WinCreate \*kaktree\* %{
		tmux-focus client0
	}
	kaktree-toggle
}
plug "alexherbo2/alacritty.kak"

# initialize kampliment, for remote control
evaluate-commands %sh{ kamp init -a }

# sorry clippy
set global ui_options terminal_assistant=none
set global tabstop 2
